default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Fe240303!
  host: localhost

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres

production:
  <<: *default
  database: MainoBlog_production
  username: MainoBlog
  password: <%= ENV["MainoBlog_DATABASE_PASSWORD"] %>
  host: localhost